image: docker:24

stages:
  - validate
  - build
  - deploy
  - test

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

before_script:
  - apk add --no-cache curl
  - chmod +x scripts/*.sh

validate_python:
  stage: validate
  tags:
    - local-docker
  script:
    - ./scripts/validate.sh

build_python:
  stage: build
  tags:
    - local-docker
  script:
    - docker compose -f python/docker-compose-python.yml build

deploy_python:
  stage: deploy
  tags:
    - local-docker
  script:
    - ./scripts/deploy-python.sh

test_python:
  stage: test
  tags:
    - local-docker
  script:
    - ./scripts/test-python.sh
